name: Libre Soy
board:
  active: 1
  user_permissions:
    can_change_initial_board_source: true
attire:
  user_permissions:
    can_toggle_visibility: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false

