library:
  visible: false
source:
  visible: true
  percentage: 0.55
board:
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: true
    can_change_initial_board_source: true
    can_edit_board: true
    can_view_size_section: true
    can_view_attire_section: false
    can_toggle_visibility: true
  active: 1
  initial_board_source: selected
execution_speed:
  user_permissions:
    can_change_speed: true
  active: high
attire:
  user_permissions:
    can_toggle_visibility: false
  visible: false
  active: null
initialDescription: true
link: ''
blocks:
  visible:
    - Poner
    - Sacar
    - Mover
    - IrAlBorde
    - Color
    - Direccion
  disabled: []
activity:
  creation_mode: advanced
name: Actividad libre

