name: Super Lucho 1
attire:
  active: Super Lucho
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - BOOM
    - RepeticionSimple
    - AlternativaSimple
    - AlternativaCompleta
    - Color
    - Direccion
    - Numero
    - puedeMover
    - hayBolitas
    - nroBolitas
    - Mis funciones
    - OperadorNumerico
    - OperadorDeComparacion
    - not
    - OperadorDeNegacion
    - OperadorLogico
    - siguiente
    - previo
    - opuesto
    - procedures_defreturn
    - Definicion de funciones simples
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - BOOM
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - RepeticionCondicional
    - AlternativaSimple
    - AlternativaCompleta
    - Color
    - Direccion
    - Numero
    - puedeMover
    - hayBolitas
    - nroBolitas
    - FuncionesPrimitivas
    - Mis funciones
    - OperadorNumerico
    - OperadorDeComparacion
    - not
    - OperadorDeNegacion
    - OperadorLogico
    - siguiente
    - previo
    - opuesto
    - procedures_defnoreturnnoparams
    - Definicion de procedimientos simples
    - procedures_defnoreturn
    - Definicion de procedimientos parametrizados
    - procedures_defreturn
    - Definicion de funciones simples
  defaultToolbox: |
    <category name="-- Biblioteca --" gbs_custom="SEPARATOR">
    </category>
      <category name="Procedimientos primitivos">
      </category>
      <category name="Funciones primitivas">
      </category>
    <category name="-- Mis operaciones --" gbs_custom="SEPARATOR">
    </category>
      <category name="Mis procedimientos" custom="PROCEDURE_CALLS">
      </category>
      <category name="Mis funciones" custom="FUNCTION_CALLS">
      </category>
    <category name="-- Comandos --" gbs_custom="SEPARATOR">
    </category>
      <category name="Básicos">
        <block type="Poner"></block>
        <block type="Sacar"></block>
        <block type="Mover"></block>
        <block type="IrAlBorde"></block>
        <block type="VaciarTablero"></block>
        <block type="BOOM"></block>
      </category>
      <category name="Repeticiones">
        <block type="RepeticionSimple"></block>
        <block type="RepeticionCondicional"></block>
      </category>
      <category name="Alternativas">
        <block type="AlternativaSimple"></block>
        <block type="AlternativaCompleta"></block>
      </category>
      <category name="Asignación">
        <block type="Asignacion"></block>
      </category>
    <category name="-- Expresiones --" gbs_custom="SEPARATOR">
    </category>
      <category name="Valores">
        <block type="ColorSelector"></block>
        <block type="DireccionSelector"></block>
        <block type="math_number"></block>
        <block type="BoolSelector"></block>
      </category>
      <category name="Expresiones primitivas">
        <block type="hayBolitas"></block>
        <block type="puedeMover"></block>
        <block type="nroBolitas"></block>
      </category>
      <category name="Operadores">
        <block type="OperadorNumerico"></block>
        <block type="OperadorDeComparacion"></block>
        <block type="OperadorLogico"></block>
        <block type="not"></block>
        <block type="siguiente"></block>
        <block type="previo"></block>
        <block type="opuesto"></block>
      </category>
    <category name="-- Definiciones --" gbs_custom="SEPARATOR">
    </category>
      <category name="Def. de procedimientos">
        <block type="procedures_defnoreturnnoparams"></block>
        <block type="procedures_defnoreturn"></block>
      </category>
      <category name="Def. de funciones">
        <block type="procedures_defreturnsimple"></block>
        <block type="procedures_defreturnsimplewithparams"></block>
        <block type="procedures_defreturn"></block>
      </category>
      <category name="Eventos">
        <block type="InteractiveLetterBinding"></block>
        <block type="InteractiveNumberBinding"></block>
        <block type="InteractiveKeyBinding"></block>
      </category>
    <category name="-- Auxiliares del docente --" gbs_custom="SEPARATOR">
    </category>
      <category name="Programas">
        <block type="Program"></block>
        <block type="InteractiveProgram"></block>
      </category>
    <category name="Bloques 'Completar'">
      <block type="ComandoCompletar"></block>
      <block type="ExpresionCompletar"></block>
      <block type="AsociacionDeTeclaCompletar"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
