name: Dino aprende a no comer chatarra
attire:
  active: La cena de Dino
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos comunes">
        <block type="RepeticionSimple"></block>
        <block type="AlternativaSimple"></block>
        <block type="AlternativaCompleta"></block>
        <block type="RepeticionCondicional"></block>
    </category>
    <category name="Expresiones comunes">
        <block type="math_number"></block>
        <block type="DireccionSelector"></block>
        <block type="OperadorLogico"></block>
        <block type="not"></block>
    </category>
    <category name="Operaciones de Dino">
        <block type="MoverADinoAl_"></block>
        <block type="CambiarADinoDeFila"></block>
        <block type="RechazarLaComida"></block>
        <block type="Comer_"></block>
        <block type="estáDinoEnElInicioDeLaFila"></block>
        <block type="hay_"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Mis funciones" custom="FUNCTION_CALLS">        </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
        <block type="procedures_defreturnsimple"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.65  