name: Prendiendo las fogatas parametrizado
attire:
  active: Prendiendo las fogatas
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos básicos">
        <block type="RepeticionSimple"></block>
        <block type="AlternativaSimple"></block>
    </category>
    <category name="Expresiones básicas">
        <block type="math_number"></block>
        <block type="DireccionSelector"></block>
    </category>
    <category name="Operaciones del Explorador">
        <block type="MoverAlExploradorAl_"></block>
        <block type="PrenderFogata"></block>
        <block type="hayFogataApagada"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturn"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  visible_edition: false
  collapse_toolbox: false
  user_permissions:
    can_view_attire_section: false
    can_edit_board: false
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_view_size_section: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.8