name: El regreso de la lista
attire:
  active: 'Cartas, letras y números'
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos básicos">
        <block type="InformarNúmero_"></block>
        <block type="RepeticionCondicional"></block>
        <block type="Asignacion"></block>
    </category>
    <category name="Operaciones de listas">
        <block type="listaDeNúmerosDelEscenario"></block>
        <block type="estáVacía_"></block>
        <block type="primerElemento_"></block>
        <block type="resto_"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Mis funciones" custom="FUNCTION_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturn"></block>
        <block type="procedures_defreturnsimplewithparams"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  visible_edition: false
  collapse_toolbox: false
  user_permissions:
    can_view_attire_section: false
    can_edit_board: false
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_view_size_section: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.65  